# Form implementation generated from reading ui file '.\editor.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ScriptEditor(object):
    def setupUi(self, ScriptEditor):
        ScriptEditor.setObjectName("ScriptEditor")
        ScriptEditor.resize(1727, 1117)
        self.centralwidget = QtWidgets.QWidget(parent=ScriptEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 321, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.B_create = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.B_create.setObjectName("B_create")
        self.horizontalLayout.addWidget(self.B_create)
        self.B_open = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.B_open.setObjectName("B_open")
        self.horizontalLayout.addWidget(self.B_open)
        self.B_save = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.B_save.setObjectName("B_save")
        self.horizontalLayout.addWidget(self.B_save)
        self.B_save_as = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.B_save_as.setObjectName("B_save_as")
        self.horizontalLayout.addWidget(self.B_save_as)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 160, 1331, 801))
        self.widget.setObjectName("widget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widget)
        self.textEdit.setGeometry(QtCore.QRect(150, 530, 1061, 231))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 470, 201, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.LW_dialouge = QtWidgets.QListWidget(parent=self.centralwidget)
        self.LW_dialouge.setGeometry(QtCore.QRect(1420, 210, 256, 711))
        self.LW_dialouge.setObjectName("LW_dialouge")
        self.B_choice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.B_choice.setGeometry(QtCore.QRect(1410, 180, 75, 23))
        self.B_choice.setObjectName("B_choice")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 140, 54, 12))
        self.label.setObjectName("label")
        ScriptEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ScriptEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1727, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        ScriptEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ScriptEditor)
        self.statusbar.setObjectName("statusbar")
        ScriptEditor.setStatusBar(self.statusbar)
        self.actionLiscence = QtGui.QAction(parent=ScriptEditor)
        self.actionLiscence.setObjectName("actionLiscence")
        self.menu.addAction(self.actionLiscence)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ScriptEditor)
        QtCore.QMetaObject.connectSlotsByName(ScriptEditor)

    def retranslateUi(self, ScriptEditor):
        _translate = QtCore.QCoreApplication.translate
        ScriptEditor.setWindowTitle(_translate("ScriptEditor", "剧本编辑器"))
        self.B_create.setText(_translate("ScriptEditor", "新建"))
        self.B_open.setText(_translate("ScriptEditor", "打开"))
        self.B_save.setText(_translate("ScriptEditor", "保存"))
        self.B_save_as.setText(_translate("ScriptEditor", "另存为"))
        self.B_choice.setText(_translate("ScriptEditor", "新建选项"))
        self.label.setText(_translate("ScriptEditor", "预览窗口"))
        self.menu.setTitle(_translate("ScriptEditor", "关于"))
        self.actionLiscence.setText(_translate("ScriptEditor", "Liscence"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScriptEditor = QtWidgets.QMainWindow()
    ui = Ui_ScriptEditor()
    ui.setupUi(ScriptEditor)
    ScriptEditor.show()
    sys.exit(app.exec())
